vmtest:
  # Virtual machine tests run in parallel and take a fair bit of memory. Use
  # resource_group to limit the concurrency of these tests so only one runs at a
  # time.
  resource_group: VM
  script:
    - python -m venv venv --system-site-packages
    - venv/bin/pip install -r testing/requirements-heavyvm.txt
    - git archive HEAD -o archive.tar.gz
    - mkdir -p tmp/overlays tmp/info
    - venv/bin/python -m testing.heavyvm.runner --image-dir /var/drgn-tools/images --vm-info-dir tmp/info --overlay-dir tmp/overlays --tarball archive.tar.gz
  artifacts:
    when: always
    paths:
      - heavyvm.xml
    reports:
      junit: heavyvm.xml

vmcore DWARF:
  script:
    - python -m venv venv --system-site-packages
    - venv/bin/pip install -r testing/requirements-vmcore.txt
    - venv/bin/python -m testing.vmcore.test -j 4 --core-directory /var/drgn-tools/vmcores
  artifacts:
    when: always
    paths:
      - vmcore.xml
    reports:
      junit: vmcore.xml

vmcore CTF:
  script:
    - python -m venv venv --system-site-packages
    - venv/bin/pip install -r testing/requirements-vmcore.txt
    - venv/bin/python -m testing.vmcore.test -j 4 --ctf --core-directory /var/drgn-tools/vmcores
  artifacts:
    when: always
    paths:
      - vmcore.xml
    reports:
      junit: vmcore.xml
