vmcore DWARF:
  script:
    - python -m testing.vmcore.test -j 4 --core-directory /var/drgn-tools/vmcores
  artifacts:
    when: always
    paths:
      - vmcore.xml
    reports:
      junit: vmcore.xml

vmcore CTF:
  script:
    - python -m testing.vmcore.test -j 4 --ctf --core-directory /var/drgn-tools/vmcores
  artifacts:
    when: always
    paths:
      - vmcore.xml
    reports:
      junit: vmcore.xml
