name: litevm test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled

jobs:
  commit-hooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        name: Set up Python
        with:
          python-version: '3.12'
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit hooks
        run: pre-commit run --all-files --show-diff-on-failure
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ol-version: [8, 9, 10]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install qemu-kvm virtiofsd zstd gzip bzip2 cpio \
                               busybox-static fio rpm2cpio podman
      - name: Setup test environment
        # We install drgn here to satisfy imports. The version doesn't really
        # matter, because this is not the version of drgn we actually use for
        # testing. Instead, we use the latest drgn RPM from Oracle Linux in the
        # test rootfs..
        run: |
          python -m venv venv
          venv/bin/pip install drgn
      - name: Enable unprivileged user namespace cloning
        # The test environment depends on unprivileged user namespaces. Ubuntu
        # 24 introduces AppArmor profiles that get in the way.
        run: |
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
      - name: Run tests
        env:
          DRGN_TOOLS_ALLOW_MISSING_LATEST: ${{ contains(github.event.pull_request.labels.*.name, 'allow-missing-latest') && '1' || '0' }}
        run: |
          venv/bin/python -m testing.vm.runner --delete-after-test -v -k ol${{ matrix.ol-version }}-*-x86_64
